import {
  AppNotification,
  FoodDonation,
  Organization,
  PlatformAnalytics,
  User,
  Volunteer,
} from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 'user-donor-1',
    name: 'ABC College Mess Administration',
    email: 'mess@abccollege.edu',
    phone: '+91 98221 44550',
    role: 'donor',
    organization: 'ABC College of Engineering & Technology',
    address: 'Campus Road, University Enclave, Kolhapur',
    latitude: 16.7042,
    longitude: 74.2441,
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=120&auto=format&fit=crop&q=80',
    created_at: '2026-08-10T08:00:00Z',
  },
  {
    id: 'user-donor-2',
    name: 'Grand Heritage Palace Banquets',
    email: 'chef@grandheritage.com',
    phone: '+91 98450 12345',
    role: 'donor',
    organization: 'Grand Heritage Hotel & Convention',
    address: 'Station Road, Shahupuri, Kolhapur',
    latitude: 16.7015,
    longitude: 74.2389,
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=120&auto=format&fit=crop&q=80',
    created_at: '2026-08-15T10:00:00Z',
  },
  {
    id: 'user-donor-3',
    name: 'Annapurna Caterers & Events',
    email: 'contact@annapurnacatering.in',
    phone: '+91 98901 88221',
    role: 'donor',
    organization: 'Annapurna Catering Services',
    address: 'Tarabai Park, Kolhapur',
    latitude: 16.7112,
    longitude: 74.2345,
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=120&auto=format&fit=crop&q=80',
    created_at: '2026-08-20T11:00:00Z',
  },
  {
    id: 'user-ngo-1',
    name: 'Annapurna Community Shelter',
    email: 'info@annapurnashelter.org',
    phone: '+91 98220 77112',
    role: 'ngo',
    organization: 'Annapurna Care Foundation',
    address: 'Rajarampuri 5th Lane, Kolhapur',
    latitude: 16.6978,
    longitude: 74.2482,
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1593113598332-cd288d649433?w=120&auto=format&fit=crop&q=80',
    created_at: '2026-08-01T09:00:00Z',
  },
  {
    id: 'user-ngo-2',
    name: 'Shanti Balgram Orphanage',
    email: 'support@shantibalgram.org',
    phone: '+91 98223 99441',
    role: 'ngo',
    organization: 'Shanti Welfare Trust',
    address: 'Nagala Park, Kolhapur',
    latitude: 16.7145,
    longitude: 74.2312,
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=120&auto=format&fit=crop&q=80',
    created_at: '2026-08-05T09:30:00Z',
  },
  {
    id: 'user-vol-1',
    name: 'Rahul Patil',
    email: 'rahul.patil@volunteer.foodbridge.org',
    phone: '+91 98600 33211',
    role: 'volunteer',
    organization: 'Rapid Rescue Network',
    address: 'Shivaji Udyamnagar, Kolhapur',
    latitude: 16.7028,
    longitude: 74.2415,
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    created_at: '2026-08-12T14:00:00Z',
  },
  {
    id: 'user-admin-1',
    name: 'Admin Command Center',
    email: 'admin@foodbridge.org',
    phone: '+91 98111 00000',
    role: 'admin',
    organization: 'FoodBridge Global Initiative',
    address: 'Civic Center, Kolhapur Municipal Corporation Zone',
    latitude: 16.705,
    longitude: 74.2433,
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    created_at: '2026-07-01T00:00:00Z',
  },
];

export const INITIAL_ORGANIZATIONS: Organization[] = [
  {
    id: 'org-1',
    name: 'Annapurna Community Shelter',
    type: 'Shelter',
    address: 'Rajarampuri 5th Lane, Kolhapur',
    latitude: 16.6978,
    longitude: 74.2482,
    capacity: 120,
    contact: 'Sunita Deshmukh',
    phone: '+91 98220 77112',
    verified: true,
    required_food_types: ['Vegetarian', 'Vegan'],
    accepted_categories: ['Cooked Meal', 'Bakery', 'Fruits', 'Vegetables', 'Dairy'],
    current_need_description: 'Urgent evening meal requirement for 85 resident workers and daily wage laborers.',
  },
  {
    id: 'org-2',
    name: 'Shanti Balgram Children Home',
    type: 'Orphanage',
    address: 'Nagala Park, Kolhapur',
    latitude: 16.7145,
    longitude: 74.2312,
    capacity: 65,
    contact: 'Pravin Joshi',
    phone: '+91 98223 99441',
    verified: true,
    required_food_types: ['Vegetarian'],
    accepted_categories: ['Cooked Meal', 'Bakery', 'Fruits', 'Dairy', 'Packaged Food'],
    current_need_description: 'Nutritious lunch and fresh fruits for 50 young children and school students.',
  },
  {
    id: 'org-3',
    name: 'Jeevan Jyoti Community Food Bank',
    type: 'Food Bank',
    address: 'Bhavani Mandap Road, Kolhapur',
    latitude: 16.6942,
    longitude: 74.2256,
    capacity: 250,
    contact: 'Vikas Kadam',
    phone: '+91 98811 55223',
    verified: true,
    required_food_types: ['Vegetarian', 'Vegan', 'Non-Vegetarian'],
    accepted_categories: ['Cooked Meal', 'Raw Food', 'Packaged Food', 'Vegetables', 'Fruits'],
    current_need_description: 'Daily ration packages and bulk warm food distribution for slum clusters.',
  },
  {
    id: 'org-4',
    name: 'Matoshree Old Age Haven',
    type: 'Shelter',
    address: 'Rankala Lake Road, Kolhapur',
    latitude: 16.6885,
    longitude: 74.2189,
    capacity: 45,
    contact: 'Meera Kulkarni',
    phone: '+91 98230 44119',
    verified: true,
    required_food_types: ['Vegetarian'],
    accepted_categories: ['Cooked Meal', 'Dairy', 'Fruits'],
    current_need_description: 'Soft-cooked wholesome meals, khichdi, and fresh milk for senior citizens.',
  },
  {
    id: 'org-5',
    name: 'Prerna Youth & Community Center',
    type: 'Community Center',
    address: 'Subhashnagar, Kolhapur',
    latitude: 16.7189,
    longitude: 74.2541,
    capacity: 90,
    contact: 'Anil Shinde',
    phone: '+91 98555 12098',
    verified: true,
    required_food_types: ['Vegetarian', 'Non-Vegetarian'],
    accepted_categories: ['Cooked Meal', 'Bakery', 'Packaged Food'],
    current_need_description: 'Surplus food distributions for night-shift sanitization workers.',
  },
  {
    id: 'org-6',
    name: 'Sneha Seva NGO Kitchen',
    type: 'NGO',
    address: 'Kasaba Bawada, Kolhapur',
    latitude: 16.7265,
    longitude: 74.2388,
    capacity: 140,
    contact: 'Radha Shinde',
    phone: '+91 98224 88771',
    verified: true,
    required_food_types: ['Vegetarian'],
    accepted_categories: ['Cooked Meal', 'Raw Food', 'Vegetables'],
    current_need_description: 'Immediate hunger relief program covering hospital patient attendants.',
  },
  {
    id: 'org-7',
    name: 'Samarpan Destitute Support Center',
    type: 'Shelter',
    address: 'Near Old Palace, Kolhapur',
    latitude: 16.7001,
    longitude: 74.2298,
    capacity: 75,
    contact: 'Ganesh More',
    phone: '+91 98904 33221',
    verified: true,
    required_food_types: ['Vegetarian'],
    accepted_categories: ['Cooked Meal', 'Bakery', 'Fruits'],
  },
  {
    id: 'org-8',
    name: 'Hope Community Dining Hall',
    type: 'Food Bank',
    address: 'Uchgaon Industrial Zone, Kolhapur',
    latitude: 16.685,
    longitude: 74.2612,
    capacity: 180,
    contact: 'Kavita Salunkhe',
    phone: '+91 98661 77234',
    verified: true,
    required_food_types: ['Vegetarian', 'Vegan', 'Non-Vegetarian'],
    accepted_categories: ['Cooked Meal', 'Packaged Food', 'Bakery', 'Raw Food'],
  },
];

export const INITIAL_VOLUNTEERS: Volunteer[] = [
  {
    id: 'vol-1',
    user_id: 'user-vol-1',
    name: 'Rahul Patil',
    phone: '+91 98600 33211',
    vehicle_type: 'Motorcycle',
    availability: 'Available',
    current_latitude: 16.7028,
    current_longitude: 74.2415,
    verified: true,
    completed_pickups: 48,
    badges: ['Rapid Responder', 'Food Runner', 'Top Rescuer'],
  },
  {
    id: 'vol-2',
    user_id: 'user-vol-2',
    name: 'Priyanka Jadhav',
    phone: '+91 98902 44118',
    vehicle_type: 'Car / Van',
    availability: 'Available',
    current_latitude: 16.7082,
    current_longitude: 74.2371,
    verified: true,
    completed_pickups: 62,
    badges: ['Community Champion', 'Rapid Responder', 'Zero Waste Partner'],
  },
  {
    id: 'vol-3',
    user_id: 'user-vol-3',
    name: 'Amit Ghatage',
    phone: '+91 98229 11099',
    vehicle_type: 'EV Cargo Bike',
    availability: 'On Delivery',
    current_latitude: 16.6991,
    current_longitude: 74.245,
    verified: true,
    completed_pickups: 35,
    badges: ['Eco Courier', 'Food Runner'],
  },
  {
    id: 'vol-4',
    user_id: 'user-vol-4',
    name: 'Sneha Bhosale',
    phone: '+91 98227 66554',
    vehicle_type: 'Motorcycle',
    availability: 'Available',
    current_latitude: 16.7121,
    current_longitude: 74.2402,
    verified: true,
    completed_pickups: 29,
    badges: ['Rapid Responder'],
  },
  {
    id: 'vol-5',
    user_id: 'user-vol-5',
    name: 'Vikram Mane',
    phone: '+91 98670 44332',
    vehicle_type: 'Car / Van',
    availability: 'Available',
    current_latitude: 16.693,
    current_longitude: 74.232,
    verified: true,
    completed_pickups: 54,
    badges: ['Bulk Hauler', 'Impact Champion'],
  },
  {
    id: 'vol-6',
    user_id: 'user-vol-6',
    name: 'Tanvi Mohite',
    phone: '+91 98451 99882',
    vehicle_type: 'EV Cargo Bike',
    availability: 'Available',
    current_latitude: 16.7065,
    current_longitude: 74.2468,
    verified: true,
    completed_pickups: 19,
    badges: ['Eco Courier'],
  },
  {
    id: 'vol-7',
    user_id: 'user-vol-7',
    name: 'Deepak Sawant',
    phone: '+91 98235 77661',
    vehicle_type: 'Motorcycle',
    availability: 'Available',
    current_latitude: 16.716,
    current_longitude: 74.233,
    verified: true,
    completed_pickups: 41,
    badges: ['Food Runner', 'Rapid Responder'],
  },
  {
    id: 'vol-8',
    user_id: 'user-vol-8',
    name: 'Anjali Powar',
    phone: '+91 98905 22114',
    vehicle_type: 'Bicycle',
    availability: 'Offline',
    current_latitude: 16.701,
    current_longitude: 74.228,
    verified: true,
    completed_pickups: 14,
    badges: ['Eco Courier'],
  },
  {
    id: 'vol-9',
    user_id: 'user-vol-9',
    name: 'Sachin Patil',
    phone: '+91 98812 44330',
    vehicle_type: 'Car / Van',
    availability: 'Available',
    current_latitude: 16.6905,
    current_longitude: 74.251,
    verified: true,
    completed_pickups: 38,
    badges: ['Bulk Hauler'],
  },
  {
    id: 'vol-10',
    user_id: 'user-vol-10',
    name: 'Neha Chougule',
    phone: '+91 98221 66779',
    vehicle_type: 'Motorcycle',
    availability: 'Available',
    current_latitude: 16.704,
    current_longitude: 74.239,
    verified: true,
    completed_pickups: 22,
    badges: ['Rapid Responder'],
  },
  {
    id: 'vol-11',
    user_id: 'user-vol-11',
    name: 'Rohan Gaikwad',
    phone: '+91 98660 11228',
    vehicle_type: 'EV Cargo Bike',
    availability: 'Available',
    current_latitude: 16.711,
    current_longitude: 74.249,
    verified: true,
    completed_pickups: 17,
    badges: ['Eco Courier'],
  },
  {
    id: 'vol-12',
    user_id: 'user-vol-12',
    name: 'Mahesh Kamble',
    phone: '+91 98452 77883',
    vehicle_type: 'Motorcycle',
    availability: 'Available',
    current_latitude: 16.698,
    current_longitude: 74.236,
    verified: true,
    completed_pickups: 45,
    badges: ['Top Rescuer'],
  },
];

// Helper to calculate future hours for realistic ISO strings
const getFutureIso = (hours: number) => {
  return new Date(Date.now() + hours * 60 * 60 * 1000).toISOString();
};
const getPastIso = (hours: number) => {
  return new Date(Date.now() - hours * 60 * 60 * 1000).toISOString();
};

export const INITIAL_DONATIONS: FoodDonation[] = [
  {
    id: 'don-demo-1',
    donor_id: 'user-donor-1',
    donor_name: 'ABC College Mess',
    food_name: 'Vegetable Biryani with Raita & Dal',
    food_category: 'Cooked Meal',
    food_type: 'Vegetarian',
    quantity: 50,
    unit: 'Meals',
    preparation_time: getPastIso(1.5),
    expiry_time: getFutureIso(2.5),
    dietary_label: 'Vegetarian, Mild Spiced, No Onion Garlic in Raita',
    description:
      'Freshly prepared surplus college hostel mess biryani packed in sanitized insulated stainless containers.',
    latitude: 16.7042,
    longitude: 74.2441,
    pickup_address: 'Campus Dining Block B, ABC College, Kolhapur',
    status: 'PUBLISHED',
    safety_status: 'VERIFIED',
    urgency: 'High',
    priority_level: 'HIGH',
    estimated_meals: 50,
    estimated_shelf_life_hours: 4,
    recommended_pickup_window: 'Within 90 minutes',
    pickup_otp: '4728',
    delivery_otp: '8391',
    assigned_ngo_id: 'org-1',
    assigned_ngo_name: 'Annapurna Community Shelter',
    assigned_volunteer_id: 'vol-1',
    assigned_volunteer_name: 'Rahul Patil',
    created_at: getPastIso(0.5),
    safety_check: {
      id: 'sc-1',
      donation_id: 'don-demo-1',
      temperature_checked: true,
      packaging_intact: true,
      preparation_time_verified: true,
      expiry_verified: true,
      contamination_check: true,
      handler_verified: true,
      quantity_verified: true,
      storage_method: 'Insulated stainless food warmer at 64°C',
      temperature_c: 64,
      overall_status: 'SAFE',
      checked_by: 'Head Chef K. Deshmukh',
      timestamp: getPastIso(0.4),
    },
  },
  {
    id: 'don-2',
    donor_id: 'user-donor-2',
    donor_name: 'Grand Heritage Hotel',
    food_name: 'Paneer Butter Masala, Jeera Rice & 80 Rotis',
    food_category: 'Cooked Meal',
    food_type: 'Vegetarian',
    quantity: 65,
    unit: 'Meals',
    preparation_time: getPastIso(2),
    expiry_time: getFutureIso(1.8),
    dietary_label: 'Vegetarian, North Indian',
    description: 'Surplus buffet dishes kept in steam chafing pans, untouched by guests.',
    latitude: 16.7015,
    longitude: 74.2389,
    pickup_address: 'Service Gate 3, Grand Heritage Hotel, Shahupuri',
    status: 'MATCHED',
    safety_status: 'VERIFIED',
    urgency: 'Critical',
    priority_level: 'CRITICAL',
    estimated_meals: 65,
    estimated_shelf_life_hours: 3.5,
    recommended_pickup_window: 'Within 60 minutes',
    pickup_otp: '5192',
    delivery_otp: '9241',
    assigned_ngo_id: 'org-2',
    assigned_ngo_name: 'Shanti Balgram Orphanage',
    created_at: getPastIso(1),
  },
  {
    id: 'don-3',
    donor_id: 'user-donor-3',
    donor_name: 'Annapurna Caterers',
    food_name: 'Chapati, Masoor Dal & Steamed Rice',
    food_category: 'Cooked Meal',
    food_type: 'Vegetarian',
    quantity: 110,
    unit: 'Meals',
    preparation_time: getPastIso(1),
    expiry_time: getFutureIso(4),
    dietary_label: 'Traditional Maharashtrian vegetarian',
    description: 'Event surplus food in sealed commercial food-grade aluminum foil trays.',
    latitude: 16.7112,
    longitude: 74.2345,
    pickup_address: 'Tarabai Park Community Kitchen, Kolhapur',
    status: 'ACCEPTED',
    safety_status: 'VERIFIED',
    urgency: 'Medium',
    priority_level: 'HIGH',
    estimated_meals: 110,
    estimated_shelf_life_hours: 5,
    recommended_pickup_window: 'Within 2 hours',
    pickup_otp: '3819',
    delivery_otp: '7721',
    assigned_ngo_id: 'org-3',
    assigned_ngo_name: 'Jeevan Jyoti Community Food Bank',
    assigned_volunteer_id: 'vol-2',
    assigned_volunteer_name: 'Priyanka Jadhav',
    created_at: getPastIso(0.8),
  },
  {
    id: 'don-4',
    donor_id: 'user-donor-1',
    donor_name: 'City Bakers Guild',
    food_name: 'Whole Wheat Sandwich Loaves & Sweet Buns',
    food_category: 'Bakery',
    food_type: 'Vegetarian',
    quantity: 85,
    unit: 'Packets',
    preparation_time: getPastIso(5),
    expiry_time: getFutureIso(28),
    dietary_label: 'Vegetarian, Eggless',
    description: 'Fresh baked surplus inventory packed in paper seal packs.',
    latitude: 16.7058,
    longitude: 74.2411,
    pickup_address: 'Baker Street, Cyber Chowk, Kolhapur',
    status: 'PUBLISHED',
    safety_status: 'VERIFIED',
    urgency: 'Low',
    priority_level: 'MEDIUM',
    estimated_meals: 85,
    estimated_shelf_life_hours: 30,
    recommended_pickup_window: 'Within 4 hours',
    created_at: getPastIso(2),
  },
  {
    id: 'don-5',
    donor_id: 'user-donor-2',
    donor_name: 'Green Grocers Market',
    food_name: 'Fresh Bananas, Apples & Seasonal Oranges',
    food_category: 'Fruits',
    food_type: 'Vegan',
    quantity: 40,
    unit: 'kg',
    preparation_time: getPastIso(6),
    expiry_time: getFutureIso(36),
    dietary_label: '100% Organic Vegan Raw Fruits',
    description: 'Grade-A surplus wholesale fruits in clean wooden crates.',
    latitude: 16.6995,
    longitude: 74.236,
    pickup_address: 'Wholesale APMC Market Yard, Kolhapur',
    status: 'IN_TRANSIT',
    safety_status: 'VERIFIED',
    urgency: 'Low',
    priority_level: 'MEDIUM',
    estimated_meals: 114,
    estimated_shelf_life_hours: 48,
    recommended_pickup_window: 'Within 5 hours',
    pickup_otp: '6214',
    delivery_otp: '1904',
    assigned_ngo_id: 'org-4',
    assigned_ngo_name: 'Matoshree Old Age Haven',
    assigned_volunteer_id: 'vol-3',
    assigned_volunteer_name: 'Amit Ghatage',
    created_at: getPastIso(3),
  },
  {
    id: 'don-6',
    donor_id: 'user-donor-1',
    donor_name: 'Royal Feast Banquet',
    food_name: 'South Indian Idli, Sambar & Chutney (Breakfast)',
    food_category: 'Cooked Meal',
    food_type: 'Vegetarian',
    quantity: 90,
    unit: 'Meals',
    preparation_time: getPastIso(12),
    expiry_time: getPastIso(2),
    dietary_label: 'Vegetarian breakfast',
    description: 'Surplus morning breakfast batches.',
    latitude: 16.7022,
    longitude: 74.2405,
    pickup_address: 'Kavala Naka Banquet Hall, Kolhapur',
    status: 'EXPIRED',
    safety_status: 'REJECTED',
    urgency: 'Critical',
    priority_level: 'LOW',
    estimated_meals: 90,
    estimated_shelf_life_hours: 4,
    recommended_pickup_window: 'Expired',
    created_at: getPastIso(14),
  },
  {
    id: 'don-7',
    donor_id: 'user-donor-3',
    donor_name: 'Sagar Ratna Restaurant',
    food_name: 'Mixed Veg Pulao & Tomato Dal',
    food_category: 'Cooked Meal',
    food_type: 'Vegetarian',
    quantity: 45,
    unit: 'Meals',
    preparation_time: getPastIso(8),
    expiry_time: getPastIso(3),
    dietary_label: 'Vegetarian',
    description: 'Surplus lunch trays safely transferred and consumed.',
    latitude: 16.7095,
    longitude: 74.238,
    pickup_address: 'New Shahupuri, Kolhapur',
    status: 'COMPLETED',
    safety_status: 'VERIFIED',
    urgency: 'Low',
    priority_level: 'MEDIUM',
    estimated_meals: 45,
    estimated_shelf_life_hours: 4,
    recommended_pickup_window: 'Completed',
    assigned_ngo_id: 'org-1',
    assigned_ngo_name: 'Annapurna Community Shelter',
    assigned_volunteer_id: 'vol-1',
    assigned_volunteer_name: 'Rahul Patil',
    created_at: getPastIso(10),
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-1',
    user_id: 'user-donor-1',
    title: 'Surplus Food Published',
    message: '50 Vegetable Biryani Meals published. AI Matching Engine is scanning nearby NGOs.',
    type: 'INFO',
    read_status: false,
    created_at: 'Just now',
  },
  {
    id: 'notif-2',
    user_id: 'user-donor-1',
    title: 'Optimal NGO Match Found!',
    message: 'Annapurna Community Shelter (0.8 km) matched with 94% compatibility score.',
    type: 'SUCCESS',
    read_status: false,
    created_at: '10 mins ago',
  },
  {
    id: 'notif-3',
    user_id: 'user-vol-1',
    title: 'New Pickup Assigned',
    message: 'Rescue Request: 50 meals from ABC College Mess to Annapurna Shelter before 8:30 PM.',
    type: 'URGENT',
    read_status: false,
    created_at: '15 mins ago',
  },
  {
    id: 'notif-4',
    user_id: 'user-ngo-1',
    title: 'Incoming Rescue Food',
    message: 'Volunteer Rahul Patil is en route with 50 hot meals. Delivery OTP: 8391.',
    type: 'INFO',
    read_status: true,
    created_at: '25 mins ago',
  },
  {
    id: 'notif-5',
    user_id: 'user-donor-1',
    title: 'Impact Milestone Achieved',
    message: 'Your organization has crossed 1,500 total meals rescued this quarter!',
    type: 'SUCCESS',
    read_status: true,
    created_at: '2 hours ago',
  },
];

export const INITIAL_ANALYTICS: PlatformAnalytics = {
  meals_rescued: 12840,
  food_diverted_kg: 4260,
  verified_donors: 87,
  partner_ngos: 42,
  active_volunteers: 124,
  successful_deliveries: 1240,
  co2e_avoided_kg: 18871.8, // 4260 kg * 4.43 factor
  people_served: 12840,
  active_donations_count: 5,
  expired_donations_count: 1,
  category_distribution: [
    { category: 'Cooked Meals', count: 742, percentage: 58 },
    { category: 'Bakery & Grains', count: 218, percentage: 17 },
    { category: 'Fresh Fruits & Veg', count: 184, percentage: 14 },
    { category: 'Dairy & Milk', count: 68, percentage: 5 },
    { category: 'Packaged Food', count: 76, percentage: 6 },
  ],
  daily_trend: [
    { day: 'Mon', meals: 1450, donations: 24 },
    { day: 'Tue', meals: 1820, donations: 31 },
    { day: 'Wed', meals: 1640, donations: 28 },
    { day: 'Thu', meals: 1980, donations: 35 },
    { day: 'Fri', meals: 2310, donations: 42 },
    { day: 'Sat', meals: 2680, donations: 49 },
    { day: 'Sun', meals: 2150, donations: 38 },
  ],
};
